name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable for Linux
      run: |
        pip install pyinstaller
        pyinstaller --onefile --name png2pdf main.py

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v3
      with:
        name: png2pdf-linux
        path: dist/png2pdf

  release-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable for Windows
      run: |
        pip install pyinstaller
        pyinstaller --onefile --name png2pdf.exe main.py

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: png2pdf-windows
        path: dist/png2pdf.exe

  create-release:
    needs: [release, release-windows]
    runs-on: ubuntu-latest

    steps:
    - name: Download Linux artifact
      uses: actions/download-artifact@v3
      with:
        name: png2pdf-linux

    - name: Download Windows artifact
      uses: actions/download-artifact@v3
      with:
        name: png2pdf-windows

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          dist/png2pdf
          dist/png2pdf.exe
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Automated release for version ${{ github.ref_name }}.
